In [18]:
# Page 125
# Ch5 Pandas
# numpy vs pandas: pandan is designed for working wiht tabular or heterogeneous data
#                  numpy i sbest for homogeneous numerical array data

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# 5.1 panda Data Structrures
# Series: one-dimensional array-like and an associated array of data labels, called its index

obj = pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [3]:
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [5]:
# 'a','b' ... as index
obj2 = pd.Series([4, 7, -5, 3], index = ['a','b','c','d'])
print(obj2)

print(obj2.values)
print(obj2.index)

a    4
b    7
c   -5
d    3
dtype: int64
[ 4  7 -5  3]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [6]:
print(obj2['a'])
print(obj2[['b','c']])

4
b    7
c   -5
dtype: int64


In [15]:
# Page 127
print( obj2[obj2 > 0])

print( obj2 * 2)

print( np.exp(obj2))

print( 'b' in obj2)


a    4
b    7
d    3
dtype: int64
a     8
b    14
c   -10
d     6
dtype: int64
a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64
True


In [7]:
print('\n-------------')
# page 128 , Python dict, convert to Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
print(obj3)
print(obj3.index)
print(obj3.values)


-------------
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')
[35000 71000 16000  5000]


In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)

print(obj4)

print(pd.isnull(obj4))

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool


In [14]:
# Page 129
# Data alignment (数据对齐)
print(obj3)
print(obj4)
print(obj3+ obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [15]:
obj4.name = 'population'
obj4.index.name = 'state'
print(obj4)

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [26]:
#index in series can be directly changed

s = pd.Series(range(4))
print(s)

# Error
# Length mismatch: Expected axis has 4 elements, 
# new values have 5 elements
# s.index = ['Bob', 'Steve', 'Jeff', 'Ryan','Sam']

names = ['Bob', 'Steve', 'Jeff', 'Ryan','Sam']
s = pd.Series(range(5), index = names)

# How ever: TypeError: Index does not support mutable operations
#obj.index[0]='Sam'
s

0    0
1    1
2    2
3    3
dtype: int64


Bob      0
Steve    1
Jeff     2
Ryan     3
Sam      4
dtype: int64

In [27]:
# page 130
# DataFrame

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
print(frame)
print(frame.head())  # show the first five rows

pd.DataFrame(data, columns=['year', 'state', 'pop'])


    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [29]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)
print(frame2.columns)
print(frame2.index)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')
Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')


In [30]:
print('\n-------------')
# Cloumn
print(frame2['state'])
print(frame2['year'])


-------------
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object
one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64
year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


In [31]:
# Row
print(frame2.loc['three'])

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


In [33]:
# Column can be modifed by assignment
frame2['debt'] = 1.6
print(frame2)

#
frame2['debt'] = np.arange(6.0)
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   1.6
two    2001    Ohio  1.7   1.6
three  2002    Ohio  3.6   1.6
four   2001  Nevada  2.4   1.6
five   2002  Nevada  2.9   1.6
six    2003  Nevada  3.2   1.6
       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0


In [32]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [34]:
frame2['eastern'] = frame2.state == 'Ohio'
print(frame2)

del frame2['eastern']

print(frame2.columns)
frame2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   5.0    False
Index(['year', 'state', 'pop', 'debt'], dtype='object')


year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [35]:
# Build a Dataframe from dictionary
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

#notice that index : no 2000, add 2003
frame3 = pd.DataFrame(pop)
print(frame3)

print('\n-----------')
frame4 = pd.DataFrame(pop,index=[2001, 2002, 2003]) 
print(frame4)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

-----------
      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN


In [52]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

print(frame3)
print('---')
print(frame3['Ohio'][:-1])
print('---')
print(frame3['Nevada'][:2])
print('---')
print(pdata)

print('---')
f5 = pd.DataFrame(pdata)
print(f5)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
---
2000    1.5
2001    1.7
Name: Ohio, dtype: float64
---
2000    NaN
2001    2.4
Name: Nevada, dtype: float64
---
{'Ohio': 2000    1.5
2001    1.7
Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
2001    2.4
Name: Nevada, dtype: float64}
---
      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4


In [53]:

# Transtation
f4 = frame3.T
print(frame3)
print(f4)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6


In [60]:
# Give name to index and columns:
print(frame3)  # before
print('---')
frame3.index.name = 'year';frame3.columns.name = 'state'
print(frame3)  # after

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
---
state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6


In [62]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [63]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [37]:
# 3 Index Objects (索引对象)
obj = pd.Series(range(3), index=['a', 'b', 'c'])
print(obj)
index = obj.index
#index[1]='d'  # Error, Index does not support mutable operations

a    0
b    1
c    2
dtype: int64


In [68]:
labels = pd.Index(np.arange(3))
print(labels)
print('---')
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

Int64Index([0, 1, 2], dtype='int64')
---


0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
# Practice
# Read student SAT Scores
