Ch5 Getting Started with pandas

Pandas contains data structures and data manipulation tools designed to make data cleaning
and analysis fast and easy in Python.

#numpy vs pandas: 
pandan is designed for working wiht tabular or heterogeneous data
numpy is best for homogeneous numerical array data

In [ ]:
# https://jupyter-notebook.readthedocs.io/en/stable/notebook.html
# https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html

In [1]:

# Ch5 Pandas
# import Series and DataFrame into the local namespace since they are so frequently used:

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
# Page 125
# 5.1 panda Data Structrures
# Series: one-dimensional array-like object and an associated array of data labels, called its index

obj = pd.Series([4,7,-5,3])
print(obj)
obj

0    4
1    7
2   -5
3    3
dtype: int64


0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [28]:
# Get values
print(obj)
print('---')
print(obj[1])
print('---')
print(obj[:3])
print('---')
print(obj[2:])

0    4
1    7
2   -5
3    3
dtype: int64
---
7
---
0    4
1    7
2   -5
dtype: int64
---
2   -5
3    3
dtype: int64


In [38]:
# Change values
print(obj)
print('---')
obj[1] = 0
obj[:3] = 10
obj

0    4
1    7
2   -5
3    3
dtype: int64
---


0    10
1    10
2    10
3     3
dtype: int64

In [32]:
# Create a Series with an index identifying each data point with a label:
# 'a','b' ... as index
# ['c', 'a', 'd'] is interpreted as a list of indices, even though it contains strings instead of integers.

obj2 = pd.Series([4, 7, -5, 3, 0], index = ['a','b','c','d','e'])

print(obj2)
print(obj2.values)
print(obj2.index)

a    4
b    7
c   -5
d    3
e    0
dtype: int64
[ 4  7 -5  3  0]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [34]:
# show one element
print(obj2['a'])

#print(obj2['b','c'])   <- Error
print('---')
# show more elements
print(obj2[['b','c']])

4
---
b    7
c   -5
dtype: int64


In [37]:
# Page 125 Filtering

res = obj2[obj2 > 0]
print( res)

print('---')
res = obj2[obj2 == 3]
print( res)


a    4
b    7
d    3
dtype: int64
---
d    3
dtype: int64


In [40]:
# Math function
print( obj2 * 2)
print('\n-------------')
print( np.exp(obj2))
print('\n-------------')
print( 'b' in obj2)


a     8
b    14
c   -10
d     6
e     0
dtype: int64

-------------
a      54.598150
b    1096.633158
c       0.006738
d      20.085537
e       1.000000
dtype: float64

-------------
True


In [41]:
# Set a Series as a fixed-length, ordered dict, as it is a mapping of index values to data values.
# page 128 , Python dict, convert to Series

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
print(obj3)
print(obj3.index)
print(obj3.values)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')
[35000 71000 16000  5000]


In [43]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)

print(obj4)

print(pd.isnull(obj4))

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool


In [44]:
# Page 129
# Data alignment
print(obj3)
print('-------------')
print(obj4)
print('-------------')
print(obj3+ obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
-------------
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
-------------
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [15]:
obj4.name = 'population'
obj4.index.name = 'state'
print(obj4)

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [45]:
#index in series can be directly changed

s = pd.Series(range(4))
print(s)

# Error
# Length mismatch: Expected axis has 4 elements, 
# new values have 5 elements
# s.index = ['Bob', 'Steve', 'Jeff', 'Ryan','Sam']

names = ['Bob', 'Steve', 'Jeff', 'Ryan','Sam']
s = pd.Series(range(5), index = names)

# How ever: TypeError: Index does not support mutable operations
#obj.index[0]='Sam'
s

0    0
1    1
2    2
3    3
dtype: int64


Bob      0
Steve    1
Jeff     2
Ryan     3
Sam      4
dtype: int64